server.port: 7000

app:
    character-service:
      host: localhost
      port: 7001
    spells-service:
        host: localhost
        port: 7002
    items-service:
        host: localhost
        port: 7003
    stats-service:
        host: localhost
        port: 7004
