version: '2.1'

services:
  character:
    build: character-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  spells:
    build: spells-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  items:
    build: Inventory-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  character-composite:
    build: character-composite-service
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  stats:
    build: stats-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker