server.port: 8443

spring.application.name: gateway

server.ssl:
  key-store-type: PKCS12
  key-store: classpath:keystore/edge.p12
  key-store-password: password
  key-alias: localhost

app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost
  auth-server: localhost



eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000

ribbon.NFLoadBalancerPingInterval: 5

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://${app.auth-server}:9999/.well-known/jwks.json

spring.cloud.gateway.routes:


- id: oauth-server
  uri: lb://auth-server
  predicates:
  - Path=/oauth/**

- id: cahracter-items
  uri: lb://api-inventory
  predicates:
  - Path=/characters/**/inventory/**

- id: character-spells
  uri: lb://api-spells
  predicates:
  - Path=/characters/**/spells/**

- id: character-stats
  uri: lb://api-stats
  predicates:
  - Path=/characters/**/stats/**


- id: items
  uri: lb://api-inventory
  predicates:
  - Path=/items/**

- id: spells
  uri: lb://api-spells
  predicates:
  - Path=/spells/**

- id: stats
  uri: lb://api-stats
  predicates:
  - Path=/stats/**


- id: character-composite
  uri: lb://character-composite
  predicates:
  - Path=/characters/*


- id: eureka-api
  uri: http://${app.eureka-server}:8761
  predicates:
  - Path=/eureka/api/{segment}
  filters:
  - SetPath=/eureka/{segment}

- id: eureka-web-start
  uri: http://${app.eureka-server}:8761
  predicates:
  - Path=/eureka/web
  filters:
  - SetPath=/

- id: eureka-web-other
  uri: http://${app.eureka-server}:8761
  predicates:
  - Path=/eureka/**

- id: host_route_200
  uri: http://httpstat.us
  predicates:
  - Host=i.feel.lucky:8080
  - Path=/headerrouting/**
  filters:
  - SetPath=/200

- id: host_route_418
  uri: http://httpstat.us
  predicates:
  - Host=im.a.teapot:8080
  - Path=/headerrouting/**
  filters:
  - SetPath=/418

- id: host_route_501
  uri: http://httpstat.us
  predicates:
  - Path=/headerrouting/**
  filters:
  - SetPath=/501

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

profiles:
    active: default
---
spring.profiles: docker

app:
    character-service:
        host: character
        port: 8080
    spells-service:
        host: spells
        port: 8080
    items-service:
      host: items
      port: 8080
    stats-service:
      host: stats
      port: 8080
    eureka-server: eureka
    auth-server: auth-server  
