server.port: 7001

spring.data.mongodb:
  host: localhost
  port: 27017
  database: character-db

logging:
    level:
        root: INFO
        dnd.microservices: DEBUG
        org.springframework.data.mongodb.core.MongoTemplate: DEBUG



---
spring.config.activate.on-profile: docker

spring.data.mongodb.host: mongodb

server.port: 8080