server.port: 7004
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*" 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring:
  application:
    name: api-stats

  data:
    mongodb:
      host: localhost
      port: 27017
      database: stats-db

  cloud.stream:
    defaultBinder: rabbit
    default.contentType: application/json
    bindings.input:
      destination: stats
      group: statsGroup

  cloud.stream.bindings.input.consumer:
    maxAttempts: 3
    backOffInitialInterval: 500
    backOffMaxInterval: 1000
    backOffMultiplier: 2.0

  cloud.stream.rabbit.bindings.input.consumer:
    autoBindDlq: true
    republishToDlq: true

  cloud.stream.kafka.bindings.input.consumer:
    enableDlq: true

  cloud.stream.kafka.binder:
    brokers: 127.0.0.1
    defaultBrokerPort: 9092

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


  logging:
    level:
      root: INFO
      dnd.microservices: DEBUG
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG



  profiles:
    active: default
---

spring:
  profiles: docker

  data:
    mongodb:
      host: mongodb

  rabbitmq.host: rabbitmq

  cloud.stream.kafka.binder.brokers: kafka

server:
  port: 8080
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*" 


eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/