server.port: 7004

spring.data.mongodb:
  host: localhost
  port: 27017
  database: stats-db

logging:
    level:
        root: INFO
        dnd.microservices: DEBUG
        org.springframework.data.mongodb.core.MongoTemplate: DEBUG


---
spring.config.activate.on-profile: docker

spring.data.mongodb.host: mongodb

server.port: 8080

---

spring.config.activate.on-profile: test

spring.data.mongodb.host: localhost

server.port: 7002

