server.port: 7004

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stats-db


  logging:
    level:
      root: INFO
      dnd.microservices: DEBUG
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG

  profiles:
    active: default
---

spring:
  profiles: docker

  data:
    mongodb:
      host: mongodb

server:
  port: 8080


