server.port: 7003

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

spring:
  datasource:
    url: jdbc:mysql://localhost/items-db
    username: user
    password: pwd
    
  logging:
    level:
        root: INFO
        dnd.microservices: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  profiles:
    active: default

spring.datasource.hikari.initializationFailTimeout: 60000
---

spring:
  profiles: docker

  datasource:
    url: jdbc:mysql://mysql/items-db

server:
  port: 8080